/*
 * bigback.c
 *
 *  Created on: 9 Jun 2025
 *      Author: electronscape
 */


// Rotated sprite generated by rotate tool
__attribute__((section(".scratch"), aligned(32)))
unsigned char bigback[960*640];